version: '2'
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=articles
  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue-vol:/var/lib/rabbitmq
volumes:
  db-vol:
  queue-vol:
